# Generated by Django 3.2.15 on 2022-08-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomRequest',
        ),
    ]
