# Generated by Django 3.2.15 on 2022-08-07 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCategory',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=250,
                     unique=True)),
                ('post_text',
                 models.TextField()),
                ('published_on',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='blogposts',
                     to=settings.AUTH_USER_MODEL)),
                ('category',
                 models.ForeignKey(
                     default=1,
                     on_delete=django.db.models.deletion.PROTECT,
                     to='blog.blogpostcategory',
                     verbose_name='Blog Category')),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
