# Generated by Django 3.2.15 on 2022-08-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcategory',
            options={'ordering': ('name',)},
        ),
    ]
