# Generated by Django 3.2.15 on 2022-08-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contactmessage_artrequestformmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('email',
                 models.EmailField(
                     max_length=254)),
                ('subject',
                 models.CharField(
                     max_length=255)),
                ('message',
                 models.TextField()),
            ],
        ),
    ]
