# Generated by Django 3.2.15 on 2022-08-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrequestformmessage',
            name='message_text',
            field=models.CharField(max_length=255),
        ),
    ]
