# Generated by Django 3.2.15 on 2022-08-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220813_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artrequestformmessage',
            name='read',
        ),
    ]
