# Generated by Django 3.2.15 on 2022-08-14 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('comment_text',
                 models.TextField()),
                ('published_on',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='commentauthor',
                     to=settings.AUTH_USER_MODEL)),
                ('product',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to='products.product')),
            ],
            options={
                'ordering': ['published_on'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
